OnionIoT/documentation

docs/device-tree-overlay/one-wire-devices.md, docs/packages/_definitions_packages.mdx, docs/packages/intro.md, docs/packages/opkg-package-manager.md, sidebars.js
Hi, I have added `OPKG Package Manager` doc in the 'issue-29'
=> OPKG Package Manager doc added

docs/STYLE-GUIDE.md
Hi @greenbreakfast, I have added `STYLE-GUIDE` in the 'issue-27'.
=> style guide addded to the top level directory

docs/packages/custom-package.md, sidebars.js
Hi @greenbreakfast I have added `create a custom package` docs in issue #31, please have a look.
=> added create a custom package chapter 

docs/packages/compile-package.md, sidebars.js
Hi @greenbreakfast I have added `Compile a Package` chapter in issue #22
=> added  `compile a package` chapter 

docs/hardware-interfaces/gpio.md, docs/hardware-interfaces/i2c.md, docs/hardware-interfaces/pin-multiplexing.md, docs/hardware-interfaces/pinouts.md, sidebars.js
Hi @greenbreakfast I have added `Pinouts` article to issue - #51 and `GPIO` article to issue - #52
=> added "Pinouts" ,"GPIO" and "Pin Multiplexing" article

docs/hardware-interfaces/pin-multiplexing.md, docs/hardware-interfaces/special-pins.md, sidebars.js
@greenbreakfast added the article `Special-Pins` for the ticket #54
=> Article Special-Pins added 

docs/packages/deploy-a-package.md, sidebars.js
Hi @greenbreakfast, I've added `Deploy a Package` for ticket #32 
Could you please take a look at it?
=> article 'deploy a package' added

docs/hardware-interfaces/ledchain.md
=> Issue 68 completed

docs/device-tree-overlay/intro.md, sidebars.js
Article rewritten and link to doc in sidebar removed. The DocCardList will now display all three docs in the parent folder.
=> Issue 65 completed

docs/device-tree-overlay/software-spi.md
Article rewritten and completed.
=> Issue 66 completed

docs/device-tree-overlay/one-wire-devices.md
One-wire devices article completed.
=> Issue 67 completed

docs/networking/ip-address-collisions.md, sidebars.js
New article Avoiding IP Address Collisions completed.
=> Issue 84 completed

docs/device-tree-overlay/software-spi.md
Updates to file for GPIO table.
=> Issue 91 completed

docs/networking/ethernet.md
Article on Ethernet Networking completed.
=> Issue 82 completed

docs/intro.md
Revisions to Introduction of Omega 2 article
=> Issue 98 completed

docs/product-overview/omega2s.md, sidebars.js
Due to conflicts on merging PR's the sidebar needed to be corrected.
=> PR to fix sidebar issues

docs/quickstart/setup-wifi.md, sidebars.js
New Setup Wifi article created.
=> Issue 128 completed

docs/quickstart/power-up.md, docs/quickstart/reference-material.md, sidebars.js
Reference material article completed. Minor change to Power Up title in power up article.
=> Issue 130 completed

docs/software/supported-languages.md, sidebars.js
Article for Omega2 Supported Languages created.
=> Issue 138 completed

docs/hardware-interfaces/gpio.md, docs/quickstart/reference-material.md
Updated link for GPIO usage in GPIO article and added link in reference material article for supported languages.
=> Updated link for GPIO usage in GPIO article.

docs/quickstart/hello-world-demo.md, sidebars.js
=> Issue 129 completed

docs/firmware/how-to-build-firmware.md
How to Build Custom Firmware article completed.
=> Issue 141 resolved

docs/hardware-interfaces/pin-multiplexing.md
Added section on how to make the pin configuration permanent.
=> Issue 151 completed.

docs/hardware-interfaces/one-wire.md
Revision to One Wire update about ghost devices.
=> Issue-148 completed

docs/hardware-interfaces/gpio.md, docusaurus.config.js, package-lock.json, package.json
=> Added google analytics tracking to docs site

docs/software/running-command-on-boot.md, docs/software/supported-languages.md, sidebars.js
New article and small adjustments to Supported Languages article.
=> New article for running a boot command

docs/packages/compile-package.md, docs/packages/custom-package.md, docs/packages/intro.md, docs/packages/opkg-package-manager.md
Updates to package definitions, package manager, create a custom package, and compile packages.
=> Updates to package articles

docs/packages/advanced-package-management.md, docs/packages/deploy-a-package.md, sidebars.js
=> Final two package articles done

docs/firmware/_build-env-notes.mdx, docs/firmware/_docker-instructions.mdx, docs/firmware/_install-deps.mdx, docs/firmware/_wsl-note.mdx, docs/firmware/how-to-build-firmware.md, docs/packages/compile-package.md, docs/packages/custom-package.md, docs/packages/intro.md, docs/packages/opkg-package-manager.md
- updated all references to previous openwrt versions
- standardized the build system setup steps in the build a package and build a firmware articles - lots of reusable content
=> Packages chapter updates

docs/packages/opkg-package-manager.md
Adjusted PR to add in only changes to the Package Manager file.
=> Added in section for Advanced Package Management

docs/firmware/_build-env-notes.mdx, docs/firmware/_docker-pull-instructions.mdx, docs/firmware/_docker-start-instructions.mdx, docs/firmware/_install-deps.mdx, docs/firmware/how-to-build-firmware.md, docs/packages/compile-package.md
- update articles to use the `onion/openwrt-builder` Docker image instead of vanilla ubuntu + installing software dependencies
- article proofreading and edits as needed
=> Update docker image used in compile package and build firmware articles

docs/product-overview/omega2.md, docs/product-overview/omega2s.md, sidebars.js
Changes:
- Linking to Omega2S Hardware Design Guide in Omega2 article as well - cc https://github.com/OnionIoT/documentation/discussions/185
- Updated info on Omega2S antenna
- Minor syntax fixes and copy edits
- Updated sidebar to group the articles related to each product
=> Updated product overview chapter

docusaurus.config.js
=> enable searching the docs site thru algolia docsearch
